apiVersion: v2
name: pull-secret
description: HyperFleet Pull Secret Adapter - Manages pull secrets in GCP Secret Manager
type: application
version: 0.1.0
appVersion: "1.0"
maintainers:
  - name: HyperFleet Team
    email: hyperfleet-team@redhat.com
keywords:
  - hyperfleet
  - adapter
  - pull-secret
  - gcp
  - secret-manager
  - kubernetes
home: https://github.com/openshift-hyperfleet/adapter-pull-secret
