apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pull-secret.labels" . | nindent 4 }}
    job-type: {{ .Values.labels.jobType }}
spec:
  backoffLimit: {{ .Values.job.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        {{- include "pull-secret.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "pull-secret.serviceAccountName" . }}
      restartPolicy: {{ .Values.job.restartPolicy }}
      containers:
      - name: pull-secret
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: GCP_PROJECT_ID
          value: {{ .Values.env.gcpProjectId | quote }}
        - name: CLUSTER_ID
          value: {{ .Values.env.clusterId | quote }}
        - name: SECRET_NAME
          value: {{ .Values.env.secretName | quote }}
        - name: PULL_SECRET_DATA
          value: {{ .Values.env.pullSecretData | quote }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
