apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pull-secret.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pull-secret.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.gcpServiceAccount }}
